# DO NOT USE THIS APPROACH IN PRODUCTION.
# THIS IS PURELY FOR PERSONAL USE.
# SEE README.md FOR DETAILS.
---
version: 5
description: "User Bash Configuration File"
repo: "https://gist.github.com/AlexAtkinson/bc765a0c143ab2bba69a738955d90abd"
license: GPLv3
author:
  name: "Alex Atkinson"
  email: "N/A"
  github: "https://github.com/AlexAtkinson"
  sponsorship: "https://github.com/sponsors/AlexAtkinson"
  linkedin: "https://www.linkedin.com/in/alex--atkinson"
lang:
  name: bash
  version: "~5.2"
  notice: "5.3 - bugs prevent adoption."
platform: "Linux, MacOS (with linuxifications)"
